version: "3"

services:
  api:
    depends_on:
      migration:
        condition: service_completed_successfully
    build:
      dockerfile: ./deploy/Dockerfile
      context: .
    volumes:
      - '.:/code'
    restart: always
    ports:
      - "8000:8000"
    env_file: .env

  db:
    image: "postgres:16.0"
    restart: always
    command: postgres -c synchronous_commit=off
    ports:
      - 5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      dockerfile: ./deploy/Dockerfile
      context: .
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - '.:/code'

volumes:
    postgres:
