"""Replace files with urls

Revision ID: 109bda8332c6
Revises: 47626c630156
Create Date: 2024-07-19 21:19:54.270189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "109bda8332c6"
down_revision: Union[str, None] = "47626c630156"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("albums", "cover", existing_type=postgresql.BYTEA(), type_=sa.String(), existing_nullable=True)
    op.alter_column("songs", "file", existing_type=postgresql.BYTEA(), type_=sa.String(), existing_nullable=False)
    op.alter_column("songs", "cover", existing_type=postgresql.BYTEA(), type_=sa.String(), existing_nullable=True)
    op.alter_column(
        "users", "profile_picture", existing_type=postgresql.BYTEA(), type_=sa.String(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "profile_picture", existing_type=sa.String(), type_=postgresql.BYTEA(), existing_nullable=True
    )
    op.alter_column("songs", "cover", existing_type=sa.String(), type_=postgresql.BYTEA(), existing_nullable=True)
    op.alter_column("songs", "file", existing_type=sa.String(), type_=postgresql.BYTEA(), existing_nullable=False)
    op.alter_column("albums", "cover", existing_type=sa.String(), type_=postgresql.BYTEA(), existing_nullable=True)
    # ### end Alembic commands ###
